version: "2"
services:
  app:
    container_name: app
    restart: always
    image: santiagormj/prueba1:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    environment: 
      - MongoURI=mongodb://mongo:27017/neoSchool
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    #ports:
     # - "27017:27017"
